[CON-08] Added descriptive assertion textes
calimero-is-near/bridge-contracts pull request #33
Opened 2022-12-14 21:01 UTC by mercepluka

2022-12-14 22:30 UTC, ijerkovic approved these changes

2022-12-14 22:39 UTC, medicz requested changes
improve wording of errors

2022-12-14 22:39 UTC, medicz commented on contracts/bridge_token_deployer/src/lib.rs
> +        require!(env::promise_results_count() == 1, "Was Expecting one and only one result");
```suggestion
        require!(env::promise_results_count() == 1, "One and only one result was expected");
```

2022-12-14 22:39 UTC, medicz commented on contracts/connector_base/src/macros.rs
> +                require!(self.deployer_account.is_none(), "Deployer account should be none");
```suggestion
                require!(self.deployer_account.is_none(), "Deployer account should not be set");
```

2022-12-14 22:39 UTC, medicz commented on contracts/connector_base/src/macros.rs
> +                require!(env::promise_results_count() == 1, "Was Expecting one and only one result");
```suggestion
                require!(env::promise_results_count() == 1, "One and only one result was expected");
```

2022-12-14 22:39 UTC, medicz commented on contracts/connector_base/src/macros.rs
> +                require!(env::promise_results_count() == 1, "Was Expecting one and only one result");
```suggestion
                require!(env::promise_results_count() == 1, "One and only one result was expected");
```

2022-12-14 22:39 UTC, medicz commented on contracts/connector_base/src/macros.rs
> +                require!(self.locker_account.is_some(), "Locker account should not be none");
```suggestion
                require!(self.locker_account.is_some(), "Locker account should be set");
```

2022-12-14 22:39 UTC, medicz commented on contracts/connector_base/src/macros.rs
> +                require!(self.locker_account.is_none(), "Locker account should be none");
```suggestion
                require!(self.locker_account.is_none(), "Locker account should not be set");
```

2022-12-14 22:39 UTC, medicz commented on contracts/connector_base/src/macros.rs
> +                require!(self.locker_account.is_some(), "Locker account should not be none");
```suggestion
                require!(self.locker_account.is_some(), "Locker account should be set");
```

2022-12-14 22:39 UTC, medicz commented on contracts/ft_connector/src/lib.rs
> +        require!(env::promise_results_count() == 1, "Was Expecting one and only one result");
```suggestion
        require!(env::promise_results_count() == 1, "One and only one result was expected");
```

2022-12-14 22:39 UTC, medicz commented on contracts/xsc_connector/src/lib.rs
> +        require!(self.locker_account.is_some(), "Locker account should not be none");
```suggestion
        require!(self.locker_account.is_some(), "Locker account should be set");
```

2022-12-14 22:39 UTC, medicz commented on contracts/xsc_connector/src/lib.rs
> +        require!(env::promise_results_count() == 1, "Was Expecting one and only one result");
```suggestion
        require!(env::promise_results_count() == 1, "One and only one result was expected");
```

2022-12-14 22:39 UTC, medicz commented on contracts/xsc_connector/src/lib.rs
> +        require!(self.locker_account.is_some(), "Locker account should not be none");
```suggestion
        require!(self.locker_account.is_some(), "Locker account should be set");
```

2022-12-14 22:39 UTC, medicz commented on contracts/xsc_connector/src/lib.rs
> +        require!(env::promise_results_count() == 1, "Was Expecting one and only one result");
```suggestion
        require!(env::promise_results_count() == 1, "One and only one result was expected");
```

2022-12-15 14:31 UTC, medicz approved these changes

2022-12-15 15:08 UTC, merged